### ISSUE TITLE
Improve configurability of verbosity behavior

### ISSUE THREAD

**Issue by moui72** [freakboy3742/pytest-tldr#29]
Hello! My team loves pytest-tldr, but we recently ran into some issues where diff truncation in the non-verbose output of pytest was interfering with debugging flaky tests. We want a way to have the tldr functionality, but have verbose output for fail/error/unexpected pass reports.

I was able to get this functionality by ripping out the "verbosity" sensitivity from pytest-tldr all together, and then running pytest in verbose mode. The blunt force version is [forked on my github account](https://github.com/moui72/pytest-tldr/commit/79262410ac02f398d8d93557aa99edffdb204f2d).

If I were to clean this up (read: restore original functionality and make it configurable) would you consider accepting a PR to add this mode?

Thanks for your work!

**Comment by freakboy3742** [comment]
We're definitely open to PRs; in this case, I'm not entirely clear what it is you are proposing. Are you talking about completely restoring the "original" pytest behavior as an option? If so - what would be the difference between that flag, and `-p no:tldr`?

**Comment by moui72** [comment]
thanks for the quick response! below is an example of what we're after
```
pytest nylas/db/tests/test_pytest_tldr.py -vvv
Preparing to test 1 packages
NYLAS_ENV=test SYNC_ENGINE_CFG_PATH=/var/folders/n5/wl978nw13gd51sp5njcdr25c0000gn/T/tmpDwQxTn ACCOUNT_CACHE_MYSQL_USER=test_user ACCOUNT_CACHE_MYSQL_DATABASE=account_cache_test_db MYSQL_USER=test_user TOTAL_WORKERS=1 MYSQL_DATABASE=unsharded_test_db py.test nylas/db/tests/test_pytest_tldr.py -vvv --timeout 90 -p no:randomly --ignore ./nylas/redwood/test/data
.F
==============================================================================
FAIL: db/tests/test_pytest_tldr.py::test_pytest_tldr[dict11-dict21]
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tyler/cloud-core/nylas/db/tests/test_pytest_tldr.py", line 18, in test_pytest_tldr
    assert dict1 == dict2
AssertionError: assert {'cheese0': 0...e11': 11, ...} == {'pasta0': 0, ...a11': 11, ...}
  Left contains 20 more items:
  {'cheese0': 0,
   'cheese1': 1,
   'cheese10': 10,
   'cheese11': 11,
   'cheese12': 12,
   'cheese13': 13,
   'cheese14': 14,
   'cheese15': 15,
   'cheese16': 16,
   'cheese17': 17,
   'cheese18': 18,
   'cheese19': 19,
   'cheese2': 2,
   'cheese3': 3,
   'cheese4': 4,
   'cheese5': 5,
   'cheese6': 6,
   'cheese7': 7,
   'cheese8': 8,
   'cheese9': 9}
  Right contains 20 more items:
  {'pasta0': 0,
   'pasta1': 1,
   'pasta10': 10,
   'pasta11': 11,
   'pasta12': 12,
   'pasta13': 13,
   'pasta14': 14,
   'pasta15': 15,
   'pasta16': 16,
   'pasta17': 17,
   'pasta18': 18,
   'pasta19': 19,
   'pasta2': 2,
   'pasta3': 3,
   'pasta4': 4,
   'pasta5': 5,
   'pasta6': 6,
   'pasta7': 7,
   'pasta8': 8,
   'pasta9': 9}
  Full diff:
  - {'cheese0': 0,
  -  'cheese1': 1,
  -  'cheese10': 10,
  -  'cheese11': 11,
  -  'cheese12': 12,
  -  'cheese13': 13,
  -  'cheese14': 14,
  -  'cheese15': 15,
  -  'cheese16': 16,
  -  'cheese17': 17,
  -  'cheese18': 18,
  -  'cheese19': 19,
  -  'cheese2': 2,
  -  'cheese3': 3,
  -  'cheese4': 4,
  -  'cheese5': 5,
  -  'cheese6': 6,
  -  'cheese7': 7,
  -  'cheese8': 8,
  -  'cheese9': 9}
  + {'pasta0': 0,
  +  'pasta1': 1,
  +  'pasta10': 10,
  +  'pasta11': 11,
  +  'pasta12': 12,
  +  'pasta13': 13,
  +  'pasta14': 14,
  +  'pasta15': 15,
  +  'pasta16': 16,
  +  'pasta17': 17,
  +  'pasta18': 18,
  +  'pasta19': 19,
  +  'pasta2': 2,
  +  'pasta3': 3,
  +  'pasta4': 4,
  +  'pasta5': 5,
  +  'pasta6': 6,
  +  'pasta7': 7,
  +  'pasta8': 8,
  +  'pasta9': 9}

------------------------------------------------------------------------------
Ran 2 tests in 0.71s

FAILED (failures=1)
```

this differs from `-p no:tldr` which gives this output
```
➜ pytest nylas/db/tests/test_pytest_tldr.py -vvv -p no:tldr
Preparing to test 1 packages
NYLAS_ENV=test SYNC_ENGINE_CFG_PATH=/var/folders/n5/wl978nw13gd51sp5njcdr25c0000gn/T/tmpge4P62 ACCOUNT_CACHE_MYSQL_USER=test_user ACCOUNT_CACHE_MYSQL_DATABASE=account_cache_test_db MYSQL_USER=test_user TOTAL_WORKERS=1 MYSQL_DATABASE=unsharded_test_db py.test nylas/db/tests/test_pytest_tldr.py -vvv -p no:tldr --timeout 90 -p no:randomly --ignore ./nylas/redwood/test/data
=================================================== test session starts ===================================================
platform darwin -- Python 2.7.17, pytest-4.6.4, py-1.8.1, pluggy-0.12.0 -- /Users/tyler/.pyenv/versions/2.7.17/envs/cloud-core-2.7/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/tyler/cloud-core/.hypothesis/examples')
rootdir: /Users/tyler/cloud-core/nylas, inifile: pytest.ini
plugins: cov-2.9.0, celery-4.2.0, hypothesis-4.57.1, mock-1.10.1, timeout-1.3.3, rerunfailures-6.0, forked-1.1.3, xdist-1.32.0, freezegun-0.4.1, snapshottest-0.5.0, shard-0.1.1
timeout: 90.0s
timeout method: signal
timeout func_only: False
collected 2 items
Running 2 items in this shard: db/tests/test_pytest_tldr.py::test_pytest_tldr[dict10-dict20], db/tests/test_pytest_tldr.py::test_pytest_tldr[dict11-dict21]

nylas/db/tests/test_pytest_tldr.py::test_pytest_tldr[dict10-dict20] PASSED                                          [ 50%]
nylas/db/tests/test_pytest_tldr.py::test_pytest_tldr[dict11-dict21] FAILED                                          [100%]

======================================================== FAILURES =========================================================
_____________________________________________ test_pytest_tldr[dict11-dict21] _____________________________________________

dict1 = {'cheese0': 0, 'cheese1': 1, 'cheese10': 10, 'cheese11': 11, ...}
dict2 = {'pasta0': 0, 'pasta1': 1, 'pasta10': 10, 'pasta11': 11, ...}

    @pytest.mark.parametrize(
        "dict1,dict2",
        [
            (
                {"cheese{x}".format(x=x): x for x in range(20)},
                {"cheese{x}".format(x=x): x for x in range(20)},
            ),
            (
                {"cheese{x}".format(x=x): x for x in range(20)},
                {"pasta{x}".format(x=x): x for x in range(20)},
            ),
        ],
    )
    def test_pytest_tldr(dict1, dict2):
>       assert dict1 == dict2
E       AssertionError: assert {'cheese0': 0...e11': 11, ...} == {'pasta0': 0, ...a11': 11, ...}
E         Left contains 20 more items:
E         {'cheese0': 0,
E          'cheese1': 1,
E          'cheese10': 10,
E          'cheese11': 11,
E          'cheese12': 12,
E          'cheese13': 13,
E          'cheese14': 14,
E          'cheese15': 15,
E          'cheese16': 16,
E          'cheese17': 17,
E          'cheese18': 18,
E          'cheese19': 19,
E          'cheese2': 2,
E          'cheese3': 3,
E          'cheese4': 4,
E          'cheese5': 5,
E          'cheese6': 6,
E          'cheese7': 7,
E          'cheese8': 8,
E          'cheese9': 9}
E         Right contains 20 more items:
E         {'pasta0': 0,
E          'pasta1': 1,
E          'pasta10': 10,
E          'pasta11': 11,
E          'pasta12': 12,
E          'pasta13': 13,
E          'pasta14': 14,
E          'pasta15': 15,
E          'pasta16': 16,
E          'pasta17': 17,
E          'pasta18': 18,
E          'pasta19': 19,
E          'pasta2': 2,
E          'pasta3': 3,
E          'pasta4': 4,
E          'pasta5': 5,
E          'pasta6': 6,
E          'pasta7': 7,
E          'pasta8': 8,
E          'pasta9': 9}
E         Full diff:
E         - {'cheese0': 0,
E         -  'cheese1': 1,
E         -  'cheese10': 10,
E         -  'cheese11': 11,
E         -  'cheese12': 12,
E         -  'cheese13': 13,
E         -  'cheese14': 14,
E         -  'cheese15': 15,
E         -  'cheese16': 16,
E         -  'cheese17': 17,
E         -  'cheese18': 18,
E         -  'cheese19': 19,
E         -  'cheese2': 2,
E         -  'cheese3': 3,
E         -  'cheese4': 4,
E         -  'cheese5': 5,
E         -  'cheese6': 6,
E         -  'cheese7': 7,
E         -  'cheese8': 8,
E         -  'cheese9': 9}
E         + {'pasta0': 0,
E         +  'pasta1': 1,
E         +  'pasta10': 10,
E         +  'pasta11': 11,
E         +  'pasta12': 12,
E         +  'pasta13': 13,
E         +  'pasta14': 14,
E         +  'pasta15': 15,
E         +  'pasta16': 16,
E         +  'pasta17': 17,
E         +  'pasta18': 18,
E         +  'pasta19': 19,
E         +  'pasta2': 2,
E         +  'pasta3': 3,
E         +  'pasta4': 4,
E         +  'pasta5': 5,
E         +  'pasta6': 6,
E         +  'pasta7': 7,
E         +  'pasta8': 8,
E         +  'pasta9': 9}

nylas/db/tests/test_pytest_tldr.py:18: AssertionError
==================================================== warnings summary =====================================================
db/tests/test_pytest_tldr.py::test_pytest_tldr[dict10-dict20]
db/tests/test_pytest_tldr.py::test_pytest_tldr[dict11-dict21]
  /Users/tyler/cloud-core/nylas/shared_test_fixtures/database_cleaner.py:56: SADeprecationWarning: The Session.close_all() method is deprecated and will be removed in a future release.  Please refer to session.close_all_sessions().
    Session.close_all()

db/tests/test_pytest_tldr.py::test_pytest_tldr[dict10-dict20]
db/tests/test_pytest_tldr.py::test_pytest_tldr[dict11-dict21]
  /Users/tyler/cloud-core/nylas/shared_test_fixtures/database_cleaner.py:92: SADeprecationWarning: The Session.close_all() method is deprecated and will be removed in a future release.  Please refer to session.close_all_sessions().
    Session.close_all()

-- Docs: https://docs.pytest.org/en/latest/warnings.html
===================================== 1 failed, 1 passed, 4 warnings in 1.08 seconds ======================================
```

it also differs from current pytest-tldr behavior:

```
➜ nylas test nylas/db/tests/test_pytest_tldr.py -vvv
Preparing to test 1 packages
NYLAS_ENV=test SYNC_ENGINE_CFG_PATH=/var/folders/n5/wl978nw13gd51sp5njcdr25c0000gn/T/tmpcrW5xQ ACCOUNT_CACHE_MYSQL_USER=test_user ACCOUNT_CACHE_MYSQL_DATABASE=account_cache_test_db MYSQL_USER=test_user TOTAL_WORKERS=1 MYSQL_DATABASE=unsharded_test_db py.test nylas/db/tests/test_pytest_tldr.py -vvv --timeout 90 -p no:randomly --ignore ./nylas/redwood/test/data
platform darwin -- Python 2.7.17
pytest==4.6.4
py==1.8.1
pluggy==0.12.0
timeout: 90.0s
timeout method: signal
timeout func_only: False
rootdir: /Users/tyler/cloud-core/nylas
inifile: pytest.ini
plugins: cov-2.9.0, celery-4.2.0, hypothesis-4.57.1, mock-1.10.1, timeout-1.3.3, rerunfailures-6.0, forked-1.1.3, xdist-1.32.0, freezegun-0.4.1, snapshottest-0.5.0, tldr-0.2.2, shard-0.1.1
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/tyler/cloud-core/.hypothesis/examples')
cachedir: .pytest_cache

------------------------------------------------------------------------------
db/tests/test_pytest_tldr.py::test_pytest_tldr[dict10-dict20] ... ok
db/tests/test_pytest_tldr.py::test_pytest_tldr[dict11-dict21] ... FAIL

==============================================================================
FAIL: db/tests/test_pytest_tldr.py::test_pytest_tldr[dict11-dict21]
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tyler/cloud-core/nylas/db/tests/test_pytest_tldr.py", line 18, in test_pytest_tldr
    assert dict1 == dict2
AssertionError: assert {'cheese0': 0...e11': 11, ...} == {'pasta0': 0, ...a11': 11, ...}
  Left contains 20 more items:
  {'cheese0': 0,
   'cheese1': 1,
   'cheese10': 10,
   'cheese11': 11,
   'cheese12': 12,
   'cheese13': 13,
   'cheese14': 14,
   'cheese15': 15,
   'cheese16': 16,
   'cheese17': 17,
   'cheese18': 18,
   'cheese19': 19,
   'cheese2': 2,
   'cheese3': 3,
   'cheese4': 4,
   'cheese5': 5,
   'cheese6': 6,
   'cheese7': 7,
   'cheese8': 8,
   'cheese9': 9}
  Right contains 20 more items:
  {'pasta0': 0,
   'pasta1': 1,
   'pasta10': 10,
   'pasta11': 11,
   'pasta12': 12,
   'pasta13': 13,
   'pasta14': 14,
   'pasta15': 15,
   'pasta16': 16,
   'pasta17': 17,
   'pasta18': 18,
   'pasta19': 19,
   'pasta2': 2,
   'pasta3': 3,
   'pasta4': 4,
   'pasta5': 5,
   'pasta6': 6,
   'pasta7': 7,
   'pasta8': 8,
   'pasta9': 9}
  Full diff:
  - {'cheese0': 0,
  -  'cheese1': 1,
  -  'cheese10': 10,
  -  'cheese11': 11,
  -  'cheese12': 12,
  -  'cheese13': 13,
  -  'cheese14': 14,
  -  'cheese15': 15,
  -  'cheese16': 16,
  -  'cheese17': 17,
  -  'cheese18': 18,
  -  'cheese19': 19,
  -  'cheese2': 2,
  -  'cheese3': 3,
  -  'cheese4': 4,
  -  'cheese5': 5,
  -  'cheese6': 6,
  -  'cheese7': 7,
  -  'cheese8': 8,
  -  'cheese9': 9}
  + {'pasta0': 0,
  +  'pasta1': 1,
  +  'pasta10': 10,
  +  'pasta11': 11,
  +  'pasta12': 12,
  +  'pasta13': 13,
  +  'pasta14': 14,
  +  'pasta15': 15,
  +  'pasta16': 16,
  +  'pasta17': 17,
  +  'pasta18': 18,
  +  'pasta19': 19,
  +  'pasta2': 2,
  +  'pasta3': 3,
  +  'pasta4': 4,
  +  'pasta5': 5,
  +  'pasta6': 6,
  +  'pasta7': 7,
  +  'pasta8': 8,
  +  'pasta9': 9}

==============================================================================
Pass: db/tests/test_pytest_tldr.py::test_pytest_tldr[dict10-dict20]
------------------------------------------------------------------------------
Found credentials in environment variables.


------------------------------------------------------------------------------
Ran 2 tests in 0.61s

FAILED (failures=1)
```

the "goal outout" resembles pytest-tldr output with verbosity at 0, but the final report (and most importantly the diff of failing assertions) is verbose

```
➜ nylas test nylas/db/tests/test_pytest_tldr.py
Preparing to test 1 packages
NYLAS_ENV=test SYNC_ENGINE_CFG_PATH=/var/folders/n5/wl978nw13gd51sp5njcdr25c0000gn/T/tmpMyKf7w ACCOUNT_CACHE_MYSQL_USER=test_user ACCOUNT_CACHE_MYSQL_DATABASE=account_cache_test_db MYSQL_USER=test_user TOTAL_WORKERS=1 MYSQL_DATABASE=unsharded_test_db py.test nylas/db/tests/test_pytest_tldr.py --timeout 90 -p no:randomly --ignore ./nylas/redwood/test/data
.F
==============================================================================
FAIL: db/tests/test_pytest_tldr.py::test_pytest_tldr[dict11-dict21]
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tyler/cloud-core/nylas/db/tests/test_pytest_tldr.py", line 18, in test_pytest_tldr
    assert dict1 == dict2
AssertionError: assert {'cheese0': 0...e11': 11, ...} == {'pasta0': 0, ...a11': 11, ...} # these truncations are what we don't want
  Left contains 20 more items:
  {'cheese0': 0,
   'cheese1': 1,
   'cheese10': 10,
   'cheese11': 11,
   'cheese12': 12,
   'cheese13': 13,... # these truncations are what we don't want

  ...Full output truncated (37 lines hidden), use '-vv' to show

------------------------------------------------------------------------------
Ran 2 tests in 0.65s

FAILED (failures=1)
```

**Comment by freakboy3742** [comment]
Closing since the original requester no longer appears to have the requirement.
