### ISSUE TITLE
0.2.3 no longer compatible with pytest <=5.x

### ISSUE THREAD

**Issue by blaxter** [freakboy3742/pytest-tldr#32]
```
$ pip install pytest==5.4.3
$ pip install pytest-tldr
$ echo "def test_foo():
    asssert True
" > tests.py
$ pytest
Traceback (most recent call last):
  File "/home/blaxter/.virtualenvs/test/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/_pytest/config/__init__.py", line 124, in main
    ret = config.hook.pytest_cmdline_main(
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/_pytest/main.py", line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/_pytest/main.py", line 228, in wrap_session
    config.hook.pytest_sessionfinish(
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/pytest_tldr.py", line 277, in pytest_sessionfinish
    self.print()
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/pytest_tldr.py", line 119, in print
    self._tw.write(end, flush=flush)
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/py/_io/terminalwriter.py", line 253, in write
    markupmsg = self.markup(msg, **kw)
  File "/home/blaxter/.virtualenvs/test/lib/python3.8/site-packages/py/_io/terminalwriter.py", line 209, in markup
    raise ValueError("unknown markup: %r" %(name,))
ValueError: unknown markup: 'flush'
```

**Comment by freakboy3742** [comment]
Thanks for the report. I can definitely reproduce this... but I'm surprised I can - because the test suite *should* be running the test suite on Pytest <4, 4, 5, *and* 6. 

Looking at the logs, it looks like we're setting up a Pytest test environment correctly, but then not actually running the tests in that environment.
