### ISSUE TITLE
`AttributeError` for `pytest v7.2.0`

### ISSUE THREAD

**Issue by rmartin16** [freakboy3742/pytest-tldr#35]
[Failing CI](https://github.com/beeware/briefcase/actions/runs/3324020664/jobs/5495092973) for beeware/briefcase#943 is suggesting `pytest-tldr` needs updates to continue working with `pytest>=7.2.0`.

```
11s
Run tox -e py --installpkg dist/*.whl
  tox -e py --installpkg dist/*.whl
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    python_version: 3.9
    pythonLocation: /opt/hostedtoolcache/Python/3.[1](https://github.com/beeware/briefcase/actions/runs/3324020664/jobs/5495092973#step:6:1)0.8/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.8/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.8/x64
    Python[2](https://github.com/beeware/briefcase/actions/runs/3324020664/jobs/5495092973#step:6:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/beeware/briefcase/actions/runs/3324020664/jobs/5495092973#step:6:3).10.8/x6[4](https://github.com/beeware/briefcase/actions/runs/3324020664/jobs/5495092973#step:6:4)
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.8/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.8/x64/lib
py create: /home/runner/work/briefcase/briefcase/.tox/py
py inst: /home/runner/work/briefcase/briefcase/.tox/.tmp/package/1/briefcase-0.3.12.dev[5](https://github.com/beeware/briefcase/actions/runs/3324020664/jobs/5495092973#step:6:5)1+gd4888321-py3-none-any.whl
py installed: arrow==1.2.3,attrs==22.1.0,binaryornot==0.4.4,briefcase @ file:///home/runner/work/briefcase/briefcase/.tox/.tmp/package/1/briefcase-0.3.12.dev51%2Bgd4888321-py3-none-any.whl,certifi==2022.9.24,chardet==5.0.0,charset-normalizer==2.1.1,click==8.1.3,commonmark==0.9.1,cookiecutter==2.1.1,coverage==[6](https://github.com/beeware/briefcase/actions/runs/3324020664/jobs/5495092973#step:6:6).5.0,exceptiongroup==1.0.0rc9,gitdb==4.0.9,GitPython==3.1.29,idna==3.4,iniconfig==1.1.1,Jinja2==3.1.2,jinja2-time==0.2.0,MarkupSafe==2.1.1,packaging==21.3,platformdirs==2.5.2,pluggy==1.0.0,psutil==5.9.3,Pygments==2.13.0,pyparsing==3.0.9,pytest==[7](https://github.com/beeware/briefcase/actions/runs/3324020664/jobs/5495092973#step:6:7).2.0,pytest-cov==4.0.0,pytest-tldr==0.2.4,python-dateutil==2.[8](https://github.com/beeware/briefcase/actions/runs/3324020664/jobs/5495092973#step:6:8).2,python-slugify==6.1.2,PyYAML==6.0,requests==2.28.1,rich==12.6.0,six==1.16.0,smmap==5.0.0,text-unidecode==1.3,tomli==2.0.1,tomli_w==1.0.0,urllib3==1.26.12
py run-test-pre: PYTHONHASHSEED='420284[9](https://github.com/beeware/briefcase/actions/runs/3324020664/jobs/5495092973#step:6:9)385'
py run-test: commands[0] | python -m coverage run -m pytest -vv
platform linux -- Python 3.[10](https://github.com/beeware/briefcase/actions/runs/3324020664/jobs/5495092973#step:6:10).8
pytest==7.2.0

INTERNALERROR> Traceback (most recent call last):

INTERNALERROR>   File "/home/runner/work/briefcase/briefcase/.tox/py/lib/python3.10/site-packages/_pytest/main.py", line 268, in wrap_session

INTERNALERROR>     config.hook.pytest_sessionstart(session=session)

INTERNALERROR>   File "/home/runner/work/briefcase/briefcase/.tox/py/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__

INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)

INTERNALERROR>   File "/home/runner/work/briefcase/briefcase/.tox/py/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec

INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)

INTERNALERROR>   File "/home/runner/work/briefcase/briefcase/.tox/py/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall

INTERNALERROR>     return outcome.get_result()

INTERNALERROR>   File "/home/runner/work/briefcase/briefcase/.tox/py/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result

INTERNALERROR>     raise ex[1].with_traceback(ex[2])

INTERNALERROR>   File "/home/runner/work/briefcase/briefcase/.tox/py/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall

INTERNALERROR>     res = hook_impl.function(*args)

INTERNALERROR>   File "/home/runner/work/briefcase/briefcase/.tox/py/lib/python3.10/site-packages/pytest_tldr.py", line [15](https://github.com/beeware/briefcase/actions/runs/3324020664/jobs/5495092973#step:6:16)5, in pytest_sessionstart

INTERNALERROR>     self.print("py=={}".format(py.__version__))

INTERNALERROR> AttributeError: module 'py' has no attribute '__version__'
ERROR: InvocationError for command /home/runner/work/briefcase/briefcase/.tox/py/bin/python -m coverage run -m pytest -vv (exited with code 3)
___________________________________ summary ____________________________________
ERROR:   py: commands failed
Error: Process completed with exit code 1.
```

This seems like the likely source (from 7.2.0 release notes):
> https://github.com/pytest-dev/pytest/issues/10396: pytest no longer depends on the py library. pytest provides a vendored copy of py.error and py.path modules but will use the py library if it is installed. If you need other py.* modules, continue to install the deprecated py library separately, otherwise it can usually be removed as a dependency.

**Comment by freakboy3742** [comment]
I was just thinking that I hadn't needed to update pytest-tldr for a while... :-)
