### ISSUE TITLE
Conflict with pytest-json

### ISSUE THREAD

**Issue by jacebrowning** [freakboy3742/pytest-tldr#9]
I'm not sure if this is a bug in `pytest-json` or `pytest-tldr`:

```
Traceback (most recent call last):
  File ".../bin/pytest", line 11, in <module>
    sys.exit(main())
  File ".../lib/python3.7/site-packages/_pytest/config/__init__.py", line 64, in main
    return config.hook.pytest_cmdline_main(config=config)
  File ".../lib/python3.7/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File ".../lib/python3.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File ".../lib/python3.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File ".../lib/python3.7/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File ".../lib/python3.7/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File ".../lib/python3.7/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File ".../lib/python3.7/site-packages/_pytest/main.py", line 208, in pytest_cmdline_main
    return wrap_session(config, _main)
  File ".../lib/python3.7/site-packages/_pytest/main.py", line 178, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File ".../lib/python3.7/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File ".../lib/python3.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File ".../lib/python3.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File ".../lib/python3.7/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File ".../lib/python3.7/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File ".../lib/python3.7/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File ".../lib/python3.7/site-packages/pytest_tldr.py", line 282, in pytest_sessionfinish
    terminalreporter=self, exitstatus=exitstatus
  File ".../lib/python3.7/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File ".../lib/python3.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File ".../lib/python3.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File ".../lib/python3.7/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File ".../lib/python3.7/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File ".../lib/python3.7/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File ".../lib/python3.7/site-packages/pytest_jsonreport/plugin.py", line 136, in pytest_terminal_summary
    terminalreporter.write_sep('-', 'JSON report')
AttributeError: 'TLDRReporter' object has no attribute 'write_sep'
```

**Comment by freakboy3742** [comment]
Looks like that might be tldr's problem - it's missing the `write_sep` method. Should be easy enough to add - thanks for the report!

**Comment by freakboy3742** [comment]
I've just released 0.1.5 that includes this fix.

**Comment by pseudotensor** [comment]
I have 0.1.5 and I still get this:
```
Traceback (most recent call last):
  File "/home/jon/.pyenv/versions/3.6.4/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/_pytest/config.py", line 61, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/_pytest/main.py", line 138, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/_pytest/main.py", line 132, in wrap_session
    exitstatus=session.exitstatus)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pytest_tldr.py", line 282, in pytest_sessionfinish
    terminalreporter=self, exitstatus=exitstatus
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/_pytest/runner.py", line 41, in pytest_terminal_summary
    tr.write_sep("=", "slowest %s test durations" % durations)
AttributeError: 'TLDRReporter' object has no attribute 'write_sep'
```

**Comment by freakboy3742** [comment]
@pseudotensor Are you sure you've got 0.1.5? Can you provide a `pip freeze` listing?

Also - what other pytest plugins do you have installed? What's your minimum case for reproducing this error?
